pipeline:
  name: demo
  identifier: demo
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454246010
        repoName: NavjitK/python
        build: <+input>
  stages:
    - step:
        type: Run
        identifier: build_python_app
        name: Build Python App
        spec:
          shell: Sh
          command: |-
            echo "Welcome to Harness CI"
            python -m pip install --upgrade pip
            pip install  pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
